version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "store-manager"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-mkhq11z33ya2"
s3_prefix = "store-manager"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
